remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: [Oleg Loshkin's Blog]
description: [I am Oleg Loshkin, a proactive and self-reliant Junior Game Programmer specializing in Audio Programming. I have graduated from the Geneva SAE Institute with a Bachelor of Science in Games Programming and wrote my bachelor thesis on real-time binaural sound spatialization.]
show_downloads: [false]