title: Oleg Loshkin
email: loshkin.oleg.95@gmail.com
author: Oleg Loshkin
description: ""
url: https://loshkinoleg.github.io
baseurl: ""
assets_dir: "http://raw.githubusercontent.com/LoshkinOleg/LoshkinOleg.github.io/main/assets"
github_username: LoshkinOleg
show_downloads: false

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

collections:
  interviews:
    output: true
  cheatsheets:
    output: true
  projects_thumbnails:
    output: true

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: false # if appearance can be switched by user
  back_home_text: "To main page.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description
  show_navbar: false # show horizontal navbar
  show_footer: false # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects
    title_academic_publications: Academic Publications
    title_blogposts: Blogposts
    title_interviews: Interviews
    title_cheatsheets: Cheatsheets

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
